version: "3.9"

services:
  db:
    image: postgres
    restart: always
    volumes:
      - "db:/var/lib/postgresql/data"
      - "$(pwd)/migrations:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

volumes:
  db: