version: "3.9"

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: deploy/web/Dockerfile
    depends_on:
      - client
    links:
      - client
    ports:
      - "8099:80"

  server:
    restart: always
    build:
      context: .
      dockerfile: deploy/server/Dockerfile
    depends_on:
      - db
    links:
      - db
    volumes:
      - "./data/meterusage.csv:/meterusage.csv"
    ports:
      - "9911:9911"

  client:
    restart: always
    build:
      context: .
      dockerfile: deploy/client/Dockerfile
    depends_on:
      - db
      - server
    links:
      - db
      - server
    ports:
      - "9912:80"

  db:
    image: postgres
    restart: always
    volumes:
      - "db:/var/lib/postgresql/data"
      - "./migrations:/docker-entrypoint-initdb.d"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

volumes:
  db: